### ISSUE TITLE
Using polymorphic vs regular Variants.

### ISSUE THREAD

**Issue by rleonid** [hammerlab/ketrew#107]
Mostly opening this as a place for discussion.

Here are some of the **positives** that I think polymorphic variants have over
regular ones (ie. ignoring type checking since they both have that):

- Easier to use during development. 
    - Reuse of the same flags/indicators.
    - Does not tie down your module to a specific interface.
    - Interface to ATD.
- Nice _sub/super_ set - behavior.
- Nicer format since you don't need the module prefix. Ie ``` `Foo 3``` as
opposed to ``` ModuleBar.Foo ``` 

Here are the **negatives**:

- Harder to debug because compilation output is verbose. It is much easier to
  detect an error of using the wrong type or not covering all union cases.
- Perhaps the _descriptive/expressive_-ness prevents the developer from
  figuring out the simplest type(s) to represent state.

In this Issue I'm going to try to identify some variants that might be nicer
expressed as strict and then provide potential changes to the code by rewriting
some. Maybe out of this process we can arrive at an agreed format/usage.

**Comment by rleonid** [comment]
Here is an interesting (weird) effect that I'm seeing with polymorphic variants.
At commit `bb2f15c75a07d3b91414916312cc654d84d7b4ea` of branch
[ketrew/split_commandliner](https://github.com/hammerlab/ketrew/commits/split_commandliner).
At this point the only thing that I've done is to move `Ketrew_document`,
`Ketrew_interaction` and `Ketrew_explorer` out of `Ketrew_command_line` into
separate modules. Afterwards, I've taken the default (_inferred_) interfaces
for the needed functions and wrote them out to a module interface.

When I compile, I get the following warnings:

```
File "src/lib/ketrew_explorer.ml", line 230, characters 6-1519:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
(`Go _|`Filter|`Follow_dependencies|`Follow_fallbacks|
`Follow_success_triggers|`Kill|`Restart|`Show_condition _|`Show_make _|
`Status|`View_json)
File "src/lib/ketrew_explorer.ml", line 285, characters 12-415:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
(`Follow_dependencies|`Follow_fallbacks|`Follow_success_triggers|`Kill|
`Restart|`Show_condition _|`Show_make _|`Status|`View_json|`Set_viewer _|
`Call _)
File "src/lib/ketrew_explorer.ml", line 333, characters 18-297:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
(`Filter|`Follow_dependencies|`Follow_fallbacks|`Follow_success_triggers|
`Kill|`Restart|`Show_condition _|`Show_make _|`Status|`View_json|
`Set_viewer _|`Call _)
File "src/lib/ketrew_explorer.ml", line 298, characters 12-2126:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
(`Go _|`Filter|`Set_viewer _|`Call _)
```

Here's what's interesting.

1. The warnings indicate that at the given points the full set of variants to
be matched should include those specified. Furthermore, the line (or function
call) in the line preceeding the match has an open (ie `[> Go _ | ...]`)
inferred type as opposed to a closed one.
2. We do **not** get these warnings when the `Ketrew_explorer` module was
inside `Ketrew_command_line`.
3. Consequently,
   - either (*less likely* but interesting) the type inference behaves
     differently across a file-module boundary then across a regular module
     boundary
   - or (*more likely*) I incorrectly specified some types in a `.mli`.

More to come.

**Comment by rleonid** [comment]
Turns out that the issue was due to hiding of
```Ocaml
type 'a menu_item = char option * Log.t * 'a
```
in the `Ketrew_interaction` interface. The parametric variable turned out to be a large collection of polymorphics (ex. ``` [> `Cancel | `Reload | `Quit]```), that signal a specific interaction we want with the chosen menu. Downstream modules use
```OCaml
val menu : ?max_per_page:int ->                                                                                                                               
           ?always_there:'a menu_item list ->                                                                                                                 
           sentence:SmartPrint.t ->                                                                                                                           
           'a menu_item list ->
             ('a, [> `Failure of string ]) t                                                                                                                  
(** Display a menu given the specified [menu_items] *)   
````
to construct menu for displaying and handling the response. The arguments `?always_there` and the final ` 'a menu_item list` must be subtypes of the final return type, they must be [covariant](http://caml.inria.fr/pub/docs/manual-ocaml-4.00/manual016.html)! The compiler knows that list are fine but not our `menu_item` type. So we need:
```Ocaml
type +'a menu_item
```

**Comment by rleonid** [comment]
I find this signature confusing. Sure it type checks, but it does not represent the logic of what this function does.

```OCaml
val explore : t ->
  (unit, [> `Client of
            [> `Http of
              [> `Archive_targets of string list
              | `Call of [> `GET | `POST ] * Uri.t
              | `Kill_targets of string list
              | `Restart_targets of string list
              | `Targets ] *
              [> `Exn of exn
              | `Json_parsing of string * [> `Exn of exn ]
              | `Unexpected_message of Ketrew_gen_protocol_v0.Down_message.t
              | `Wrong_json of Json.t
              | `Wrong_response of Cohttp.Response.t * string ]
            | `Server_error_response of [> `Call of [> `GET | `POST ] * Uri.t ]
            * string ]
        | `Database of Trakeva.Error.t
        | `Database_unavailable of string
        | `Failure of string
        | `IO of [> `Read_file_exn of string * exn
                 | `Write_file_exn of string * exn ]
        | `Missing_data of string
        | `Persistent_state of [> `Deserilization of string ]
        | `System of [> `File_info of string ] * [> `Exn of exn ]
        | `Target of [> `Deserilization of string ] ]) Deferred_result.t
(** [explore ~client exploration_states] runs a read-eval loop to explore and
    interact with targets.*)
```

**Comment by smondet** [comment]
Well, it starts the “explorer” (it's a UI, has only side effects, so `unit`) and can fail in many ways, the type just enumerates which ones (which actually gives some insight of the logic of the function; a bit like “cheap algebraic effects”).

Some of them should be more precise, I don't like `` `Failure _` and `` `Missing_data _`.

**Comment by rleonid** [comment]
I think it is distracting.
```OCaml
val explore : t ->  (unit, InteractiveFailure.t]) Deferred_result.t
```
even a little bit of compression makes it more palatable.

```OCaml
val explore : t ->
  (unit, [> `Client of ClientError.t
         | `Database of Trakeva.Error.t
         | `Database_unavailable of string
         | `Failure of string
         | `IO of [> `Read_file_exn of string * exn
                  | `Write_file_exn of string * exn ]
         | `Missing_data of string
         | `Persistent_state of [> `Deserilization of string ]
         | `System of [> `File_info of string ] * [> `Exn of exn ]
         | `Target of [> `Deserilization of string ] ]) Deferred_result.t
