### ISSUE TITLE
Get rid of Toml

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#124]

**Comment by smondet** [comment]
I was thinking of experimenting with this:

Have `Ketrew_configuration.t` (de)serializable to Json and then, when config-files are needed, be able to generate the Json from an ocaml script.

If the user has their config in `my_client.ml`:

```
let client_profile = Ketrew_configuration.create (* ... *)
let default = Ketrew_configuration.create (* ... *)
```
Ketrew (binary) can append some ocaml to that file, call `ocaml file.ml` and collect the Json output and load it :)
(or compiling a `.cmxs` would be a short-cut but would make things less hackable)

**Comment by rleonid** [comment]
I'm confused. Once it is in `json` why does the user have their config in  `my_client.ml`?

**Comment by smondet** [comment]
It could be pure Json, but Json is not meant to be read/writen by humans, so providing optional help through an ocaml file would be cool.

**Comment by rleonid** [comment]
But you have something different in mind besides `ketrew init` ?

**Comment by smondet** [comment]
What I have in mind kind of replaces `ketrew init` with running an ocaml file that dumps Json (but also allows to do that every time).

On top of that, I want to add support for more than one “profile” in the same file (which would over-fix https://github.com/hammerlab/ketrew/issues/41).
Having a full language for the configuration allows to share values, and “generate” configurations.

**Comment by rleonid** [comment]
I don't think it's a good idea to replace `ketrew init` if it requires another application. Probably better to keep it self-sufficient (What about having a default file deployed with ketrew?).

Do you think that `json` wouldn't be able to represent logic for multiple profiles? I can't think of any specific limitations in json.

**Comment by smondet** [comment]
> I don't think it's a good idea to replace ketrew init if it requires another application. Probably better to keep it self-sufficient (What about having a default file deployed with ketrew?).

I don't understand. What other application?

> Do you think that json wouldn't be able to represent logic for multiple profiles? I can't think of any specific limitations in json.

Yes, Json can and would "represent" the multiple profiles. But since Json is very painful to write and maintain, there would be also the option of having it generated by a small ocaml script.

**Comment by rleonid** [comment]
By other application I meant `OCaml`. Do we want to allow people to use `Ketrew` without it? There could be command line arguments to Ketrew to generate specific cases, for example: `ketrew init server`.

**Comment by smondet** [comment]
Yes my latest plan is that Ketrew is going to look at different paths for configuration (the order, or what's the default not yet fixed):

- `.ketrew/config.json` → parse the json,
- `.ketrew/config.ml` → call ocaml on it, collect `stdout`, parse the json
- `.ketrew/config.sh` → call `./config.sh` collect `stdout`, parse the json
- `.ketrew/config.url` → wget, parse the json

(The actual paths can be overridden like now of course)
Then, the user will have the choice of weapon.
