### ISSUE TITLE
Move from ATD to OCaml+PPX

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#125]

**Comment by smondet** [comment]
Why moving:

- simplify build system
- do not depend on an old version of CConv
- be less restrictive about the kind of types we can use (normal Vs polymorphic variants, types that are not automatically serializable but we can provide `{of,to}_json`, like GADTs)
- use `ppx` for other things (equality, show, etc)

Why not moving:

- sentimental attachement to `atd2cconv`
- interoperability (ATD would allow someone to write a code-generator for an inferior language)
- OCaml ≤ 4.02.0

**Comment by avsm** [comment]
Why couldn't you write a code generator from OCaml+PPX?  Seems like just another deriving backend.

**Comment by smondet** [comment]
Good point @avsm!

**Comment by rleonid** [comment]
My only concern is that getting rid of `ATD` and using ppx would require future users to write code generators in `OCaml` for their desired language as opposed to parsing and converting `ATD`.

**Comment by smondet** [comment]
I think the event of someone without ocaml knowledge attempting that is too unlikely to guide this decision.
And in any case OCaml+ppx → ATD (or Avro, thrift, Piqi, etc.) is actually easy to write.

**Comment by smondet** [comment]
Another argument for PPX, is that the documentation generation would be less catastrophic.

**Comment by smondet** [comment]
An argument against PPX: it breaks `bisect` (based on `camlp4`).

(partially switched there: https://github.com/hammerlab/ketrew/tree/ppx_yojson)

**Comment by rleonid** [comment]
hardly a strong argument.
