### ISSUE TITLE
document authorized_tokens setup

### ISSUE THREAD

**Issue by arahuja** [hammerlab/ketrew#130]

**Comment by hammer** [comment]
http://seb.mondet.org/software/ketrew/Developer_Documentation.html?

**Comment by arahuja** [comment]
Perhaps I missing something on the page, but there is a command to generate a test one, but I didn't see anything that explains what it does, why its needed or what the columns in the file are.

Also, there should probably be something not under developer documentation as its needed to run ketrew

**Comment by smondet** [comment]
yes it's only "mentioned" there: http://seb.mondet.org/software/ketrew/The_Configuration_File.html

needs more love
