### ISSUE TITLE
should invalid debug-level throw an error?

### ISSUE THREAD

**Issue by arahuja** [hammerlab/ketrew#132]
The documentation says

```
debug-level: integer specifying the amount of verbose messages: 0: none, 1: verbose, 2: very verbose
```

I set `debug-level = 4` which ketrew seems happy with 
```
ketrew status
[ketrew: debug] Calling Lwt_main.run
[ketrew: debug]
    Configuration: setting globals:
        debug_level: 4
```

What does this do and should this be possible?  Is it just anything >= 2 is "very verbose"?

**Comment by smondet** [comment]
Let's say yes, `anythin >= 2` is very-verbose for now (and leaving larger numbers for the future, potentially very-very-*-verbose)
