### ISSUE TITLE
Selecting target loses page number

### ISSUE THREAD

**Issue by arahuja** [hammerlab/ketrew#141]
In the Target Explorer, if I select a target to view and then `q` to go back, it goes back to the first page of the Target Explorer.  It would be nice if it could jump back to the page I was on.

**Comment by smondet** [comment]
That should have been fixed on master (PR from 4 days ago I think). Did you try with a client recent enough?

Also in https://github.com/hammerlab/ketrew/issues/140, the `>`, `<` keys should have disapeared (it's `n`, `p`, `h` for home now).

**Comment by arahuja** [comment]
Ah ok, I may not have reinstalled the client, will try that

**Comment by arahuja** [comment]
Not a problem in latest master
