### ISSUE TITLE
Client Batch Download

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#153]
Diff: https://github.com/hammerlab/ketrew/compare/af84455...88a681f

The idea is to make the client (the text-UI) download less at once; and in the same time batch target-downloads together.

Then the prefetching and display parameters are added to the configuration (both through “live” changeable settings and in the configuration file).

**Comment by rleonid** [comment]
Looks fine.

**Comment by smondet** [comment]
Thanks!
