### ISSUE TITLE
Code-review: `cbreak` in the configuration

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#157]
Diff: <https://github.com/hammerlab/ketrew/compare/639efec...3e5ea83>

This improves the configuration of the UI, it could already be configured
through the variable `WITH_CBREAK` but now it is also a proper value in
`Configuration.ui`.

I used the opportunity to improve the formatting in `Configuration.log` (which
is what's shown by “`ketrew print-conf`”).

**Comment by rleonid** [comment]
Looks good.
