### ISSUE TITLE
Code-review: even better daemonization

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#166]
Diff: <https://github.com/hammerlab/ketrew/compare/3e5ea83...f8c6bf9>

This addresses:

- https://github.com/hammerlab/ketrew/issues/156#issuecomment-96000496
- https://github.com/hammerlab/ketrew/issues/156#issuecomment-96039310
- Issue #165 (It updates also `make test-env` and the documentation).

**Comment by rleonid** [comment]
> `daemonize`: if `true`, ask the server to detach from the current terminal; if
>  you use this option it is required to provide absolute paths for all other
>  parameters requiring paths (daemonization changes theprocess directory to `/`)

`daemonize`: if `true` the server will detach from the current terminal. If you use this option, all paths must be provided as absolutes as the daemonization changes the process directory to '/'.

Looks fine.
