### ISSUE TITLE
Code-review: Fix daemonization with python 3

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#171]
Diff: <https://github.com/hammerlab/ketrew/compare/051973c...f5b9aba>

It's all in relation to fixing the issue #169.

It was difficult to debug because I had forgot to fill the `?log` arguments in some places in the `Target.Automaton.transition` function (in the case of `` `Fatal`` errors).

The generated script by `Ketrew_daemonize` should hopefully now work with python 2.4+ and python 3+.

I tested quickly “live” but I created #170 for further integration testing.

**Comment by rleonid** [comment]
The `OCaml` looks fine, certainly #170 as an integration test would be useful.
