### ISSUE TITLE
Code-review: MLIs for Ketrew_{server,client}

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#178]
Diff: <https://github.com/hammerlab/ketrew/compare/9480c44...1c1786c>

This fixes #54.

It also adds the submodule `Client.Error` to clean-up a bit.

The name `restart_target` taking a list of targets felt wrong; `restart` is
consistent with `kill`.

**Comment by rleonid** [comment]
Looks good. Thanks for cleaning it up.
