### ISSUE TITLE
Code-review: Documentation of the EDSL (mli)

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#191]
Diff: <https://github.com/hammerlab/ketrew/compare/8da0c94...f599da6>

This is just doucmentation, it's related to the issue
[`hammerlab/biokepi#62`](https://github.com/hammerlab/biokepi/issues/62).

If it's OK, I'll add it to the `doc.1.0.0` branch and hence the website too.

**Comment by rleonid** [comment]
for `target` :
  
1. machanism -> m**e**chanism
2. 'or alike' what do you mean by this? I'd rather be explicit and say 'by fallback'
3. list of dependencies -> list of *the* dependencies

for `file_target` :

1. will be the file on the -> will be **a** file on the

otherwise looks good.
