### ISSUE TITLE
Code-review: Fix #193.

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#194]
Diff: <https://github.com/hammerlab/ketrew/compare/f599da6...bec6de0>

1. Add new option to daemonize: `?no_log_is_ok`</br>
The default value is `false` which is the previous behavior and the JSon parsing
is backwards compatible thanks to the annotation: `[@default false]`.<br/>
We still wait for the starting-timeout before checking that condition; this
seems that the behavior one would expect.
2. Free YARN backend from shared filesystems</br>
This is an attempt at fixing
[#193](https://github.com/hammerlab/ketrew/issues/193), it requires more testing
(I did some testing with the branch
[`intergration-tests-i62`](https://github.com/hammerlab/ketrew/tree/intergration-tests-i62) but not enough).

This will require further tunning anyway, since `` `Unknown`` maybe should be a non-fatal error instead of `` `Still_running _``. And other “final-statuses” of YARN could be interpreted, cf. [doc](https://hadoop.apache.org/docs/r2.4.1/hadoop-yarn/hadoop-yarn-site/YarnCommands.html#application).

EDIT: formatting

**Comment by rleonid** [comment]
for `target` :
  
1. machanism -> m**e**chanism
2. 'or alike' what do you mean by this? I'd rather be explicit and say 'by fallback'
3. list of dependencies -> list of *the* dependencies

for `file_target` :

1. will be the file on the -> will be **a** file on the

otherwise looks good.
