### ISSUE TITLE
DistributedShell defaults to request a single vcore

### ISSUE THREAD

**Issue by arahuja** [hammerlab/ketrew#209]
`DistributedShell` has a `-container_vcores` argument to request a larger number of cores which should probably be used for tasks that plan on using more.

This is fairly easy to add to `hadoop_distshell_call` in `yarn.ml` but not sure how much of the `Run_parameters.distributed_shell_parameters` can be updated without changing the external API.

**Comment by smondet** [comment]
I checked the backwards compatibility (:+1:)  and I ran a Yarn job with container_vcores:3:

<img width="163" alt="screenshot 2015-09-25 17 56 02" src="https://cloud.githubusercontent.com/assets/617111/10113066/b995b318-63ae-11e5-8826-c5d7e6067046.png">

(the application master 1 + the container 3)

:sunglasses:
