### ISSUE TITLE
Email notifications for failures

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#213]
In a meeting this was mentioned to be a failing of other offerings; having to manually check for failures.

**Comment by smondet** [comment]
Being able to hook to a notification system globally can be interesting indeed.

But note that this can already be part of the pipelines designed by people, e.g. in Biokepi one can add intermediate nodes easily and they can send emails or anything:

```ocaml
    let wrap_node pipeline node =
      let open Biokepi.Common.KEDSL in
(* ... *)
      workflow_node node#product ~equivalence:`None ~name ~make
        ~edges:[
          depends_on node;
          if_fails_activate some_email_sending_target;
        ]
    in
    let compiler =
      Biokepi.Pipeline.Compiler.create 
        ~wrap_vcf_node:wrap_node ~wrap_bam_node:wrap_node
        ~processors ~reference_build ~work_dir ~machine () in
```

**Comment by arahuja** [comment]
Something I found interesting about the API here that I didn't understand is why `node` as a dependency needs to appear twice

For example in 
```
      workflow_node node#product ~equivalence:`None ~name ~make
        ~edges:[
          depends_on node;
```

`workflow_node` is wrapping the product of the `node`, but the `depends_on node` is still necessary?

**Comment by smondet** [comment]
@arahuja (That's more of a biokepi issue then) the `#product` tells `workflow_node` what it makes (i.e. the same thing as the parent `node`) but doesn't tell that it's a hard dependency, we need the `depends_on` to actually get the bioinformatics step called.

**Comment by smondet** [comment]
→ https://github.com/hammerlab/epidisco/blob/master/src/lib/qc.ml
