### ISSUE TITLE
Clicking a tab (for backend-specific queries) should refresh/reissue the query

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#215]
Currently you need to click the tab + click the refresh button to refresh the output shown. Instead, when clicking the tab (either an unselected tab or the currently selected tab), the query should be reissued and the text update. The refresh button might just serve to check for new queries/tabs instead.

![screen recording 2015-10-14 at 07 05 pm](https://cloud.githubusercontent.com/assets/167803/10500455/68dd271a-72a6-11e5-8081-473bc0541c20.gif)

**Comment by smondet** [comment]
Fixed: https://github.com/hammerlab/ketrew/pull/314
