### ISSUE TITLE
Change server daemonization method

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#229]
Lwt really doesn't like daemons, it keeps breaking in different ways
(like https://github.com/mirleft/ocaml-tls/issues/302).

**Comment by smondet** [comment]
- https://github.com/mirleft/ocaml-tls/issues/302#issuecomment-151334698
- https://groups.google.com/d/msg/ocaml-core/N8dUkus8URA/camkTl8ACAAJ

**Comment by hammer** [comment]
Hmm "I would advise against doing the Unix daemonization dance.". What would he advise, then?

**Comment by smondet** [comment]
See also    https://github.com/ocsigen/ocsigenserver/pull/27
and http://gitweb.skylable.com/gitweb/?p=libres3.git;a=commitdiff;h=90822043f2e9ea18dd971067fc9b5ea0b3e6bd35

**Comment by smondet** [comment]
Exorcised by #480 :fire:
