### ISSUE TITLE
Correct usage of while_sequential

### ISSUE THREAD

**Issue by rleonid** [hammerlab/ketrew#233]
I'm a bit confused by this usage of [while_sequential](https://github.com/hammerlab/ketrew/blob/master/src/lib/server.ml#L300), doesn't the 2nd part (ie after `>><`) prevent `~f` from failing?

**Comment by smondet** [comment]
Yes `~f` does not fail there so the whole list is traversed every time which the intended behavior.

**Comment by rleonid** [comment]
In that case can we replace it with just a `List.map` or more specifically roll it into the `filter_map` below?

**Comment by smondet** [comment]
Yeah but `get_target` returns a `Deferred_result.t` so `List.map` or `List.filter_map` would not be enough to ensure it's sequential.

```ocaml
List.fold ~init:(return ()) more ~f:(fun prev_m id ->
   prev_m >>= fun () ->
   Engine.get_target ....
)
````

the `bind` makes the traversal sequential which is what `while_sequential` “hides” gracefully :)

**Comment by rleonid** [comment]
sigh.
