### ISSUE TITLE
JSONP callback in Server

### ISSUE THREAD

**Issue by rleonid** [hammerlab/ketrew#235]
Since a callback can be missing from a [request](https://github.com/hammerlab/ketrew/blob/master/src/lib/server.ml#L602), perhaps it is better to handle it the same way as a missing [body](https://github.com/hammerlab/ketrew/blob/master/src/lib/server.ml#L591) ?

I tried some googling to see if `missing_callback` was some special Javascript by my searches were empty, perhaps @ihodes or @danvk can chime in with some expertise?

**Comment by smondet** [comment]
Yes it should be a `wrong_request` error.

**Comment by rleonid** [comment]
Ok, cool. I'll change this into a bug and fix.

**Comment by rleonid** [comment]
Fixed in #237
