### ISSUE TITLE
Confusion about binds vs destructs

### ISSUE THREAD

**Issue by rleonid** [hammerlab/ketrew#236]
@smondet Help!

I'm confused how this [bind](https://github.com/hammerlab/ketrew/blob/master/src/lib/server.ml#L667) and this [one](https://github.com/hammerlab/ketrew/blob/master/src/lib/server.ml#L675) compile. Shouldn't they be destructs? `>><`

**Comment by smondet** [comment]
Those are within the `Lwt`-only monad: https://github.com/hammerlab/ketrew/blob/master/src/lib/server.ml#L656

**Comment by rleonid** [comment]
ooooohhhhh
