### ISSUE TITLE
Document why make, the Build_process argument is optional in eDSL.target

### ISSUE THREAD

**Issue by rleonid** [hammerlab/ketrew#241]
What's the use case for having "no-ops" as default targets?

**Comment by smondet** [comment]
There are many use cases, 

- one may want to make sure a condition is there and fail early to tell the user (like some software configuration that requires human intervention, e.g. [`google/skicka`](https://github.com/google/skicka) for my backups)
- a target can be used only to put dependencies together (that's often the case to submit a common ancestor for a bunch of stuff to do) → https://github.com/hammerlab/biokepi/blob/master/src/app/main.ml#L179
- or to treat input data in a uniform way (“everything is a workflow node” [there](https://github.com/hammerlab/biokepi/blob/master/src/lib/pipeline.ml#L454))

**Comment by rleonid** [comment]
Excellent! Time to add this to the documentation!

**Comment by smondet** [comment]
@rleonid do you have any idea of where to document that?
should we create `src/doc/FAQ.md` so that it shows up on the website?
(also @hammer , @ihodes ?)

**Comment by rleonid** [comment]
The `FAQ` idea seems fine with me.
