### ISSUE TITLE
Describe plugin architecture 

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#246]
1) Why/what they are
2) How they're used
3) How to make a custom plugin

**Comment by smondet** [comment]
Could you be more precise on what's missing?
http://seb.mondet.org/software/ketrew/Long-Running_Plugins.html

**Comment by smondet** [comment]
At least a link form there to how to make ketrew load them: http://seb.mondet.org/software/ketrew/api/Ketrew.Configuration.html#VALcreate

**Comment by ihodes** [comment]
From that docs page, while a good start, it's unclear what they are (I only know from reading the code the past week + asking you about them), how they might compare to "short running plugins" (which don't exist AFAIK?), and the directions to make one could probably stand to be expanded for someone with a little less OCaml experience. Plugins seem sort of core to using Ketrew in a serious way.

**Comment by smondet** [comment]
Not that "core", since the  `Yarn` backend became part of the main repo, nobody AFAIK has used plugins :)

But yes, an overall description (from there) of what they "are" is missing.
