### ISSUE TITLE
Default filter in web GUI (and interactive mode?) should show "root targets"

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#248]
That is, `(is-activated-by-user)`.

**Comment by smondet** [comment]
@arahuja, @ihodes you both should agree :)
https://github.com/hammerlab/ketrew/issues/211

**Comment by smondet** [comment]
Note that I think @ihodes meant the "default" as the one when you land on the table, while @arahuja meant the one that gets added when the text-input is empty and you submit.

**Comment by ihodes** [comment]
#211 makes sense to me; that's what I'd expect in having no filters.
