### ISSUE TITLE
Merge "advanced" API from Biokepi

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#287]
Though I'd prefer if we called it the "API" and the current API the "base API"; the Biokepi version uses better verbiage and is simpler (although it uses a row type + parametric types, I think it's still easier to understand, and can be understood and used without understanding that).

**Comment by smondet** [comment]
I agree, I also much prefer the parametric version.
(PS: it's there: https://github.com/hammerlab/biokepi/blob/master/src/lib/common.ml#L74)

We would need to discuss names of things:

- Advanced API / API / Base API / Legacy API / Easy API?
- It's also the occasion to potentially change names of function arguments:
  http://seb.mondet.org/software/ketrew/api/Ketrew.EDSL.html#VALtarget

**Comment by rleonid** [comment]
Just one API.

**Comment by smondet** [comment]
@rleonid we should not break the backwards compatibility now (too much code uses the current one).

**Comment by smondet** [comment]
@rleonid moreover the `workflow_node` API is much less OCaml-beginner friendly (carrying around a type parameter can be more compilcated).

**Comment by rleonid** [comment]
I disagree, I would argue that carrying around a type parameter is the point of using a language like OCaml.

**Comment by smondet** [comment]
Just referencing the previous discussion: https://github.com/hammerlab/ketrew/pull/182
