### ISSUE TITLE
Add a version contraint for ppx_deriving in the opam package dependency

### ISSUE THREAD

**Issue by chambart** [hammerlab/ketrew#291]
I did try installing Ketrew 2.0 with ppx_deriving 2.1 installed and it failed.
It did work with ppx_deriving 3.0.

**Comment by smondet** [comment]
Indeed we have so far the constraint on `ppx_deriving_yojson` but not `ppx_deriving` itself
https://github.com/ocaml/opam-repository/blob/master/packages/ketrew/ketrew.2.0.0/opam#L26

**Comment by smondet** [comment]
The fix made it to the mothership opam-repo!
