### ISSUE TITLE
Weird YARN error

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#317]
The file is there, I checked.

```
16/01/11 13:55:20 FATAL distributedshell.Client: Error running Client java.io.FileNotFoundException: File /.../KT/ketrew_2016-01-11-19h56m16s087ms-UTC_603092089/monitored_script does not exist at 
org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:534) at
org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:747) at
org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:524) at
org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:424) at
 org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:340) at
 org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1944) at
 org.apache.hadoop.yarn.applications.distributedshell.Client.run(Client.java:556) at
 org.apache.hadoop.yarn.applications.distributedshell.Client.main(Client.java:215)
```

**Comment by hammer** [comment]
I wonder if it's related to the YARN restart that @zgiles did?

**Comment by zgiles** [comment]
This looks more like just a normal file not found error rather than a broken YARN error.
Not sure where "there" is. Perhaps a reference to an NFS mount that is down or something?
All I did with YARN was remove some nodes from YARN

**Comment by smondet** [comment]
@zgiles yes it is on NFS, my home dir. Can see the file from the login node, and from one or 2 random compute nodes I tried (but much later so maybe it's an NFS "sync delay").

**Comment by smondet** [comment]
Oh my path was starting with a double slash !
`//something/something/...` 

Must have a meaning for YARN...

**Comment by smondet** [comment]
The problem is only with leading slashes it seems …
Closing this one in favor of → https://github.com/hammerlab/ketrew/issues/318
