### ISSUE TITLE
Fix author list

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#336]
- [x] add @ihodes (in `opam` file and maybe licence headers)
- [x] Fix [zenodo DOI](http://dx.doi.org/10.5281/zenodo.45295): add everybody, fix “Sebastien”'s spelling

**Comment by ihodes** [comment]
Done & done.

**Comment by ihodes** [comment]
https://github.com/hammerlab/ketrew/pull/337/files

**Comment by smondet** [comment]
Thanks !
