### ISSUE TITLE
Hard to determine which dependency failed

### ISSUE THREAD

**Issue by iskandr** [hammerlab/ketrew#345]
Currently the Ketrew web UI requires manual recursive exploration of the dependency tree to determine why a target failed. I would prefer to just get a list of failing leaf nodes.

**Comment by smondet** [comment]
![not-dependency-dead](https://cloud.githubusercontent.com/assets/617111/12961777/261356d0-d010-11e5-9619-9e02a7efe08b.png)

**Comment by iskandr** [comment]
Cool, thanks for pointing me to the help page. I'm still not clear how to use this to drill down into the failing components of a target.

**Comment by iskandr** [comment]
For anyone else who comes across this thread: change your filter to `(and (created-in-the-past (weeks 4)) (is-failed) (not (is-dependency-dead)))`. One caveat is that this shows you all failed nodes from any user-submitted job. 

@smondet It would be nice to add a `(child-of node-id)` predicate to allow filtering for children of my one target of interest. 

It would also be nice to have this filter setting be enabled via a button click on failed jobs (rather than having to type or copy it).
