### ISSUE TITLE
Need to recover from "failures" of timeout that aren't actually failures

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#353]
Have some YARN jobs still running that Ketrew considered failures because it couldn't check the status of them for 60+ seconds. Now it can check it, but the jobs have already "failed", but the computations are still running. This is dangerous because 

1) they could be modifying paths still 
2) if I resubmit, (1) could mess things up
3) this is actually recoverable, so a potential waste of resources
4) we should be sure workflow nodes that didn't fail right (e.g. a YARN job is still running; we don't have reasonable proof that it's dead) are in a different status and we continue to try to clean them up

**Comment by smondet** [comment]
Fixed in the above commit.
