### ISSUE TITLE
Server keeps crashing

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#354]

**Comment by smondet** [comment]
From offline investigation two kinds of crashes were observed:

-  `/tmp` dir getting cleaned-out under Ketrew's feet (PR on the way)
- Too-many-open-files: while waiting for https://github.com/mirage/ocaml-conduit/pull/115 one can use OCaml-TLS instead of OpenSSL.

**Comment by smondet** [comment]
The issue above has been fixed.
