### ISSUE TITLE
GUI Server slowness/lags 

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#355]
Takes a long time to open new tabs, or load the list of nodes, for example.

**Comment by ihodes** [comment]
This is still a problem; seeing "Fetching targets" for a long time. This is a server with only 10k nodes (5 runs of our pipeline) and nothing else on it. We're expecting our workflow to increase quite a bit over the coming weeks, too!

**Comment by iskandr** [comment]
Getting past "Fetching targets" seems to take somewhere between 2 and 10 minutes today.

**Comment by smondet** [comment]
This was fixed also.
