### ISSUE TITLE
Trouble starting server (addr in use after `ketrew stop`)

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#373]
```
[me@node .ketrew]$ ketrew stop -P daemon
[ketrew: Warning]
    Write-operation timeout; the server must not be running, try
    sub-command `status`
[me@node .ketrew]$ ketrew stop -P server
[ketrew: Warning]
    Write-operation timeout; the server must not be running, try
    sub-command `status`
[me@node .ketrew]$ ketrew start -P daemon
[ketrew] Started the daemon, now waiting for the server
status.
[ketrew] The server seems to have failed to start
(connection timeouted).
[ketrew]
    Here is the latest start-error:
2016-03-02-21h13m06s195ms-UTC (PID: 23522)
Error starting the server: Server seems to be already running
```

**Comment by ihodes** [comment]
```
$ ketrew start -P server
ketrew: "bind" failed: Address already in use
```

**Comment by smondet** [comment]
OK I think I understand better this one.

A Ketrew server, if it uses the `daemonize` on localhost (i.e. not over SSH); it seems that (at east in some configurations) the daemonized process inherits the open socket, and then when restarting the server that address is already in use.

**Comment by smondet** [comment]
OK I don't know how to fix this nicely for now.
Cf. https://github.com/mirage/ocaml-conduit/issues/119

In a fork of `conduit` with `Lwt_unix.set_close_on_exec` used on the listen socket, I got this issue fixed. 


Another ugly idea would be to get the file-descriptor number with some other hack (`/proc/` is only on linux, parsing the output of `lsof` seems crazy, …) and then getting a `Unix.file_descr` with `Obj.magic`
(it's an `int` https://github.com/ocaml/ocaml/blob/trunk/otherlibs/unix/unix.ml#L213).

**Comment by ihodes** [comment]
Is it possible to have the child process close all possible open FDs (just iterate 0 through max_fd), and then start e.g. the YARN/distributed shell subprocess. That way they don't keep a hold on the socket.

**Comment by smondet** [comment]
OK I did this: https://github.com/mirage/ocaml-conduit/pull/123

So you should get a temporary fix for this with:

```
opam pin add conduit -k git "https://github.com/smondet/ocaml-conduit.git#set-close-on-exec"
```

**Comment by smondet** [comment]
The previous one is wrong, please use:

```
opam pin add conduit -k git "https://github.com/smondet/ocaml-conduit.git#for-ketrew"
```

**Comment by smondet** [comment]
The close-on-exec was merged upstream.
