### ISSUE TITLE
Submitting to (a small) Ketrew server very slow

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#377]
Taking a long time to show up in the table view, though the notification tab shows "received". There are maybe ~15 nodes total on this server, so it's not loaded. 

![](http://link.isaachodes.io/392I24461C3D/Screen%20Shot%202016-03-03%20at%208.31.17%20PM.png)

![](http://link.isaachodes.io/0H3V0m1C3L1n/Screen%20Shot%202016-03-03%20at%208.31.04%20PM.png)

logs for the server: http://link.isaachodes.io/171H321f0y2k/test-server.log

**Comment by smondet** [comment]
When it shows on the notification area it means that the workflow has been received and stored, and it's ready to start (even if the power is shut down, Ketrew will eventually get it to start when restarting)
Then it can take a while to get started if the engine is busy doing stuff before (if SSH connections; `yarn status` calls take a while they delay everybody).

(It's not the number of nodes that impacts that time, one single node that tries to get some info over SSH until the connection times-out can delay everything; up to a whole minute per node I think by default)

**Comment by ihodes** [comment]
Hmm, over 12 hours later still nothing; I don't think it's just waiting for a SSH timeout

**Comment by smondet** [comment]
oh OK so then it's engine that broke and stopped doing things. Most likely the DB is in a weird state.

**Comment by ihodes** [comment]
Is there something I can do to recover? 

```
$ ketrew start -P test-server
[ketrew] Started the daemon, now waiting for the server
status.
[ketrew: ERROR]
    Reading "/tmp/ketrew_2016-03-04-18h10m15s008ms-UTC_089809344" with
    timeout 10. failed.
[ketrew] The server seems to have failed to start
(connection refused).
[ketrew: ERROR]
    Cannot read the server-start error:
    Exception while reading
    "/hpc/users/hodesi01/.ketrew/test.server.log/server_start_error.txt":
    Unix.Unix_error(Unix.ENOENT, "open",
    "/hpc/users/hodesi01/.ketrew/test.server.log/server_start_error.txt")
```
