### ISSUE TITLE
Creating SSH Named Host fails to show created host until page is refreshed

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/ketrew#380]
After refresh, it had the "Fetching stuff" spinner as well for a while.

**Comment by smondet** [comment]
OK, checked-out offline, network was down/slow.

**Comment by ryan-williams** [comment]
Can the UI be more clear about what's going on?

**Comment by smondet** [comment]
@ryan-williams ah yes for sure, it's not finished (main reason why 2.1.0 is not released). https://github.com/hammerlab/ketrew/milestones/Two-point-one
