### ISSUE TITLE
Add interfaces and implementation to delete targets

### ISSUE THREAD

**Issue by rleonid** [hammerlab/ketrew#398]
from the gui and from interact.

**Comment by smondet** [comment]
What do you mean by "delete"?
Remove them from any view that the UI could provide?

**Comment by rleonid** [comment]
Yes, from the UI. Though, I could see some utility in removing the targets that are remembered by the Ketrew database; in cases when you submitted a target that works but doesn't do precisely the right thing.

**Comment by smondet** [comment]
OK, just reminding that once a target/w-node is "finished" it doesn't count anymore in equivalence computations or anything; it's just there for inspection. I.e. if it is buggy it won't break other things; and resubmitting will be "Fresh".

Also note you can use the query language to never-see some targets; but it's tru it's not very handy for now.

**Comment by smondet** [comment]
We decided to go the other way (try to be able to see as much as possible)
