### ISSUE TITLE
Cannot switch between tabs sometimes

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#399]
In JS console `Uncaught 0,248,Failure,-3,signal value undefined yet`

This seems to happen when the web UI is very slow; targets take forever/don't load, and then I can't switch between tabs. 

This is difficult to repro.

**Comment by smondet** [comment]
Did this happen while any other time than when your browser was running out of sockets? (#400)

**Comment by ihodes** [comment]
Yes it was. So maybe this'll somehow go away when we fix that?

**Comment by smondet** [comment]
I don't know; with the chrome limitation,  the UI was locked waiting for data. And `signal value undefined` sounds like a `React` exception.
So maybe the UI being locked just exposed some very-low-level race-condition (all `React.S.t`'s in the webUI are created with an initial value and then just change value; but I've seen weird things before).

**Comment by ihodes** [comment]
Makes sense. If/when I have more time, I'll try to repro to file a better. In the meantime, will close this.
