### ISSUE TITLE
Track time spent on each node

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#407]
Would be nice if this were a first-class value, displayed in the UI and easily accessible via the API. 

A way to see the total time spent across 2 nodes (e.g. a root not and some dependency several nodes away) would also be great. 

This would let us optimize our pipelines and get an idea of how long certain parts take. Eventually a UI for navigating this would be awesome.

**Comment by smondet** [comment]
Duplicate of #285.
