### ISSUE TITLE
Yarn backend should truncate names that are too long

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#411]
The limit on our cluster, for example, is 255. I just tried submitting one that was 280 characters long. It didn't work out.

**Comment by hammer** [comment]
Gross. Can we query YARN for this value?

**Comment by smondet** [comment]
I think YARN uses the name to create directories and hits the maximal filename size: http://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash

**Comment by ihodes** [comment]
Also, long names tend to make the UI of the RM funky, from @ryan-williams:

http://f.cl.ly/items/1L2G2U3B0s1U3m060Z42/Screen%20Shot%202016-03-29%20at%201.15.22%20PM.png
