### ISSUE TITLE
Error showing things still building, but nothing running

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#509]
looking at the status, I get 

> non-fatal error "Client.IO: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")" (check-running)

**Comment by smondet** [comment]
It looks like a setup problem; like Ketrew cannot talk to Coclobas?

**Comment by ihodes** [comment]
I don't think it's setup; it worked for a few days, then stopped working.
Restarting the docker image/relaunching Ketrew et al got it working it.

**Comment by smondet** [comment]
Did you just restart or the Sqlite DBs got deleted?

it can also be the coclobas container running out disk space or alike.

**Comment by ihodes** [comment]
Just a restart; I don't think I'm running out of disk space (unless Docker has a smaller pool?)

**Comment by smondet** [comment]
This could be a coclobas bug (but not Ketrew's; it just could not talk to coclobas and reported all the info it had, thanks Unix…); closing for now unless we have more data on how this can be reproduced.

**Comment by ihodes** [comment]
What info would be helpful to gather next time this occurs?

**Comment by smondet** [comment]
@ihodes 

- the Coclobas logs, 
- the status of the container
- whether `http://<coclobas-host:port>/status` returns something (with `curl` for example)
