### ISSUE TITLE
`exec` commands in the Ketrew GUI shouldn't be rendered within divs

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#520]
This makes it impossible to copy-paste these commands (as there are no spaced when copied), which makes debugging painful.

**Comment by smondet** [comment]
Well, they also are not escaped, if you copy-paste an `exec` even with spaces, you won't get the same behavior anyway.

**Comment by ihodes** [comment]
At least in the common cases that I've run into, I do. Just adding spaced/formatting it as a single `<code>` block would really help out.
