### ISSUE TITLE
GUI view for daemonize like the Coclobas Ketrew backend `display`

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#521]

**Comment by smondet** [comment]
it's already there (and for all other backends too), maybe the name is not that right

![image](https://cloud.githubusercontent.com/assets/617111/24369581/7740a226-12f2-11e7-9540-552b718316cf.png)

**Comment by ihodes** [comment]
Aha, knew it was there! Filed https://github.com/hammerlab/ketrew/issues/523
