### ISSUE TITLE
example server docker container from web page tutorial does not start

### ISSUE THREAD

**Issue by nilsbecker** [hammerlab/ketrew#534]
docker complains about a non-existent path `/home/smondet/biokepi-work-dir`

**Comment by smondet** [comment]
Oops indeed I need to re-generate the docker-compose configuration.

**Comment by smondet** [comment]
@nilsbecker  if you have a moment to try, #536 it should work now.

**Comment by nilsbecker** [comment]
yes! the server is running now. don't know yet what i'm doing but so far so good!

(ketrew pinned to the github repo, mac os, 4.03.0 switch as in the tutorial)
