### ISSUE TITLE
Add test coverage tool

### ISSUE THREAD

**Issue by hammer** [hammerlab/ketrew#59]
[ZAMCOV](http://www.algo-prog.info/zamcov/web/)?

**Comment by rleonid** [comment]
How about [bisect](http://bisect.x9c.fr/)? Last updated (2012-11) and available as a package in opam.

**Comment by smondet** [comment]
This was fixed and broken again (because of PPX Vs Camlp4):

```
File "src/pure/ketrew_pervasives.ml", line 100, characters 33-34:
Parse error: "end" expected after [str_items] (in [module_expr])
File "src/pure/ketrew_pervasives.ml", line 1:
Error: Error while running external preprocessor
Command line: camlp4o str.cma /Users/sebastienmondet/.opam/4.02.1/lib/bisect/bisect_pp.cmo 'src/pure/ketrew_pervasives.ml' > /var/folders/2n/6hsnw69536bf_j1k1jdrclyw0000gn/T/ocamlpp7cb7ac

Command exited with code 2.
```

**Comment by smondet** [comment]
We should fix or remove.

@rleonid, any ideas?

**Comment by rleonid** [comment]
bisect is supposed to work with ppx, but when I last checked that version did not compile. I'll look into making it work.

**Comment by smondet** [comment]
And we even got rid of the `myocamlbuild.ml` !
https://github.com/hammerlab/ketrew/commit/2999044ad1de1a82e53d3821cbf5a29ab0544e5f
