### ISSUE TITLE
Use ocaml-git (with or without Irmin)

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#79]
Since https://github.com/mirage/ocaml-git/pull/16 `ocaml-git` got rid of `Core_kernel`.

We should use it, and get `Ketrew_database` out of Ketrew as an independent library.

**Comment by smondet** [comment]
This is not relevant any more.

**Comment by samoht** [comment]
why not? :-)

**Comment by smondet** [comment]
@samoht  The issue is there now: https://github.com/smondet/trakeva/issues/6 :)
